# Generated by Django 4.2.30 on 2026-04-21 07:37

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='权限代码')),
                ('name', models.CharField(max_length=255, verbose_name='权限名称')),
                ('category', models.CharField(choices=[('user', '用户管理'), ('project', '项目管理'), ('stage', '阶段管理'), ('task', '任务管理'), ('file', '文件管理'), ('system', '系统管理')], max_length=50, verbose_name='权限分类')),
                ('description', models.TextField(blank=True, verbose_name='权限描述')),
                ('is_system', models.BooleanField(default=True, verbose_name='是否系统权限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'plat_permission',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL标识')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('status', models.CharField(choices=[('active', '活跃'), ('archived', '已归档'), ('deleted', '已删除')], default='active', max_length=20, verbose_name='状态')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'plat_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(max_length=50, verbose_name='阶段标识')),
                ('name', models.CharField(max_length=255, verbose_name='阶段名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目阶段',
                'verbose_name_plural': '项目阶段',
                'db_table': 'plat_projectstage',
                'ordering': ['project', 'order'],
                'unique_together': {('project', 'stage_key')},
            },
        ),
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('is_system', models.BooleanField(default=True, verbose_name='是否系统预设')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色模板',
                'verbose_name_plural': '角色模板',
                'db_table': 'plat_roletemplate',
            },
        ),
        migrations.CreateModel(
            name='StageStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_key', models.CharField(max_length=50, verbose_name='步骤标识')),
                ('name', models.CharField(max_length=255, verbose_name='步骤名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('can_skip', models.BooleanField(default=True, verbose_name='是否可跳过')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.projectstage', verbose_name='所属阶段')),
            ],
            options={
                'verbose_name': '阶段步骤',
                'verbose_name_plural': '阶段步骤',
                'db_table': 'plat_stagestep',
                'ordering': ['stage', 'order'],
                'unique_together': {('stage', 'step_key')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('researcher', '研究者'), ('viewer', '访客')], default='researcher', max_length=20, verbose_name='角色')),
                ('quota_projects', models.IntegerField(default=10, verbose_name='项目配额')),
                ('quota_storage_mb', models.IntegerField(default=5120, verbose_name='存储配额(MB)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否已审核')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户配置',
                'verbose_name_plural': '用户配置',
                'db_table': 'plat_userprofile',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=50, verbose_name='任务类型')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery任务ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.FloatField(default=0.0, verbose_name='进度(0-1)')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='任务结果')),
                ('logs', models.TextField(blank=True, verbose_name='运行日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='任务配置')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project', verbose_name='所属项目')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.projectstage', verbose_name='所属阶段')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.stagestep', verbose_name='所属步骤')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'plat_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file', models.FileField(upload_to=core.models.data_file_upload_path, verbose_name='文件')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='文件类型')),
                ('data_category', models.CharField(choices=[('input', '输入数据'), ('output', '输出数据'), ('intermediate', '中间数据')], default='input', max_length=20, verbose_name='数据类别')),
                ('source', models.CharField(choices=[('upload', '用户上传'), ('tool_generated', '工具生成'), ('imported', '导入')], default='upload', max_length=50, verbose_name='来源')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.project', verbose_name='所属项目')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.projectstage', verbose_name='所属阶段')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.stagestep', verbose_name='所属步骤')),
            ],
            options={
                'verbose_name': '数据文件',
                'verbose_name_plural': '数据文件',
                'db_table': 'plat_datafile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='授权人')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission', verbose_name='权限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户权限',
                'verbose_name_plural': '用户权限',
                'db_table': 'plat_userpermission',
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='RoleTemplatePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission', verbose_name='权限')),
                ('role_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_permissions', to='core.roletemplate', verbose_name='角色模板')),
            ],
            options={
                'verbose_name': '角色模板权限',
                'verbose_name_plural': '角色模板权限',
                'db_table': 'plat_roletemplatepermission',
                'unique_together': {('role_template', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='DataFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('change_summary', models.TextField(blank=True, verbose_name='变更说明')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.datafile', verbose_name='数据文件')),
            ],
            options={
                'verbose_name': '文件版本',
                'verbose_name_plural': '文件版本',
                'db_table': 'plat_datafileversion',
                'ordering': ['data_file', '-version'],
                'unique_together': {('data_file', 'version')},
            },
        ),
    ]
