# Generated by Django 5.2.11 on 2026-02-28 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': '文档(旧)', 'verbose_name_plural': '文档(旧)'},
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('SEARCH', '文献检索'), ('SCREEN_1', '文献初筛'), ('SCREEN_2', '文献复筛'), ('QUALITY', '文献质量评价'), ('EXTRACT', '数据提取'), ('META', 'Meta分析')], max_length=20, verbose_name='阶段类型')),
                ('status', models.CharField(default='PENDING', max_length=20, verbose_name='阶段状态')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目阶段',
                'verbose_name_plural': '项目阶段',
                'unique_together': {('project', 'stage_type')},
            },
        ),
        migrations.CreateModel(
            name='StageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stage_data/%Y/%m/%d/', verbose_name='文件')),
                ('filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('data_type', models.CharField(choices=[('INPUT', '输入数据'), ('OUTPUT', '输出数据')], default='INPUT', max_length=10, verbose_name='数据类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('source', models.CharField(default='UPLOAD', max_length=50, verbose_name='来源')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='core.stage', verbose_name='所属阶段')),
            ],
            options={
                'verbose_name': '阶段数据',
                'verbose_name_plural': '阶段数据',
            },
        ),
    ]
