# Generated by Django 5.2.11 on 2026-02-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_document_options_stage_stagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='元数据'),
        ),
    ]
