# Generated by Django 4.2.30 on 2026-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='log_file',
            field=models.CharField(blank=True, max_length=500, verbose_name='日志文件路径'),
        ),
    ]
