# Generated by Django 5.2.11 on 2026-02-28 15:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stage_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedata',
            name='file',
            field=models.FileField(upload_to=core.models.stage_data_upload_path, verbose_name='文件'),
        ),
    ]
