# Generated by Django 4.2.30 on 2026-04-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_stagedata_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractiontask',
            name='log_file',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='日志文件路径'),
        ),
        migrations.AlterField(
            model_name='extractiontask',
            name='logs',
            field=models.TextField(blank=True, null=True, verbose_name='运行日志（已废弃，使用log_file）'),
        ),
        migrations.AlterField(
            model_name='extractiontask',
            name='status',
            field=models.CharField(choices=[('PENDING', '等待中'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('STOPPED', '已停止')], default='PENDING', max_length=20, verbose_name='任务状态'),
        ),
    ]
