# Generated by Django 4.2.30 on 2026-07-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='concurrency_limit',
            field=models.IntegerField(default=2, verbose_name='AI筛选并发档位'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='是否被封禁'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='是否已审核'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('user', '普通用户'), ('researcher', '研究者'), ('viewer', '访客')], default='user', max_length=20, verbose_name='角色'),
        ),
    ]
