# Generated by Django 4.2.30 on 2026-08-03 07:01

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_migrate_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='当前余额(credits)')),
                ('total_granted', models.IntegerField(default=0, verbose_name='累计赠送(credits)')),
                ('total_consumed', models.IntegerField(default=0, verbose_name='累计消耗(credits)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '额度账户',
                'verbose_name_plural': '额度账户',
                'db_table': 'plat_creditaccount',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('grant', '赠送'), ('recharge', '充值'), ('consume', '消耗'), ('refund', '退款'), ('adjust', '管理员调整')], max_length=20, verbose_name='类型')),
                ('amount', models.IntegerField(verbose_name='金额(credits, 正=加/负=减)')),
                ('balance_after', models.IntegerField(verbose_name='操作后余额')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.creditaccount', verbose_name='账户')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_ops', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '额度流水',
                'verbose_name_plural': '额度流水',
                'db_table': 'plat_credittransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(upload_to=core.models.data_file_upload_path, verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datafileversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roletemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roletemplatepermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stagestep',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='模型名称')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='输入 tokens')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='输出 tokens')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总 tokens')),
                ('credits_consumed', models.IntegerField(default=0, verbose_name='折算 credits')),
                ('ref_count', models.IntegerField(default=1, verbose_name='本次处理文献篇数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_logs', to='core.task', verbose_name='任务')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_logs', to='core.credittransaction', verbose_name='对应流水')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Token 用量日志',
                'verbose_name_plural': 'Token 用量日志',
                'db_table': 'plat_tokenusagelog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='core.task', verbose_name='关联任务'),
        ),
    ]
