# Generated by Django 4.2.30 on 2026-08-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_billing_credit_account_transaction_tokenusagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('queuing', '排队等待'), ('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止'), ('superseded', '已被续传替代')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
