# Generated by Django 4.2.30 on 2026-08-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_status_queuing'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='注册IP')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('success', models.BooleanField(default=True, verbose_name='是否注册成功')),
                ('fail_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='失败原因')),
                ('email_verified', models.BooleanField(default=False, verbose_name='邮箱已验证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '注册日志',
                'verbose_name_plural': '注册日志',
                'db_table': 'plat_registrationlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='idx_reg_ip_time')],
            },
        ),
    ]
