# Generated by Django 4.2.30 on 2026-08-04 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_registrationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='兑换码')),
                ('credits', models.IntegerField(verbose_name='面值(credits)')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间（null=永不过期）')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_codes_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_codes_used', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '兑换码',
                'verbose_name_plural': '兑换码',
                'db_table': 'plat_rechargecode',
                'ordering': ['-created_at'],
            },
        ),
    ]
