# Generated by Django 4.2.30 on 2026-08-12 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_rechargecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='txn_type',
            field=models.CharField(choices=[('grant', '赠送'), ('recharge', '充值'), ('consume', '消耗'), ('refund', '退款'), ('adjust', '管理员调整'), ('admin_usage', '管理员用量')], max_length=20, verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='ManualReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_xml', models.CharField(max_length=500, verbose_name='对应 XML 文件名')),
                ('ai_decision', models.CharField(blank=True, default='', max_length=20, verbose_name='AI 原始决定 (included/excluded/error)')),
                ('ai_reason', models.TextField(blank=True, default='', verbose_name='AI 排除理由（原文）')),
                ('decision', models.CharField(choices=[('included', '纳入'), ('excluded', '排除'), ('pending', '待定')], max_length=20, verbose_name='人工最终决定')),
                ('reason', models.TextField(blank=True, default='', verbose_name='人工标注理由')),
                ('is_override', models.BooleanField(default=False, verbose_name='是否与 AI 判断不同（人工覆写）')),
                ('reviewed_at', models.DateTimeField(auto_now=True, verbose_name='最后审阅时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_reviews', to='core.project', verbose_name='所属项目')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审阅人')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_reviews', to='core.stagestep', verbose_name='所属步骤（review）')),
            ],
            options={
                'verbose_name': '人工审阅记录',
                'verbose_name_plural': '人工审阅记录',
                'db_table': 'plat_manualreview',
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['project', 'decision'], name='idx_mr_project_decision')],
                'unique_together': {('project', 'source_xml')},
            },
        ),
    ]
