# Generated by Django 4.2.30 on 2026-08-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_manual_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualreview',
            name='consensus',
            field=models.CharField(choices=[('included', '一致纳入'), ('excluded', '一致排除'), ('conflict', '存在分歧'), ('pending', '待处理')], default='pending', max_length=20, verbose_name='多模型共识结论'),
        ),
        migrations.AddField(
            model_name='manualreview',
            name='multi_model_results',
            field=models.JSONField(blank=True, default=list, help_text='[{"model_id": "gpt-4o", "model_name": "GPT-4o", "decision": "included", "reason": "", "tokens": {}}]', verbose_name='多模型筛选结果'),
        ),
        migrations.AlterField(
            model_name='manualreview',
            name='ai_decision',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='AI 原始决定 (included/excluded/conflict/error)'),
        ),
        migrations.AlterField(
            model_name='manualreview',
            name='decision',
            field=models.CharField(choices=[('included', '纳入'), ('excluded', '排除'), ('pending', '待定'), ('conflict', '分歧（待人工定夺）')], max_length=20, verbose_name='人工最终决定'),
        ),
        migrations.AddIndex(
            model_name='manualreview',
            index=models.Index(fields=['project', 'consensus'], name='idx_mr_project_consensus'),
        ),
    ]
