# Generated by Django 4.2.30 on 2026-08-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_multi_model_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualreview',
            name='notes',
            field=models.JSONField(blank=True, default=list, help_text='[{"content": "备注内容", "created_at": "2024-01-01T12:00:00", "user": "admin"}]', verbose_name='备注列表'),
        ),
    ]
