# Generated by Django 4.2.30 on 2026-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_qa_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qachart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qadomainresult',
            name='applicability_result',
            field=models.CharField(choices=[('low', '低风险/低担忧'), ('high', '高风险/高担忧'), ('unclear', '不清楚'), ('pending', '待确认'), ('na', '不适用')], default='pending', max_length=20, verbose_name='适用性担忧结果'),
        ),
        migrations.AlterField(
            model_name='qadomainresult',
            name='bias_risk_result',
            field=models.CharField(choices=[('low', '低风险/低担忧'), ('high', '高风险/高担忧'), ('unclear', '不清楚'), ('pending', '待确认'), ('na', '不适用')], default='pending', max_length=20, verbose_name='风险偏倚结果'),
        ),
        migrations.AlterField(
            model_name='qadomainresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qareference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qasignalitem',
            name='consistency',
            field=models.CharField(choices=[('single', '单模型'), ('consistent', '模型一致'), ('divergent', '模型分歧'), ('partial', '部分生成'), ('failed', '生成失败')], default='single', max_length=20, verbose_name='一致性状态'),
        ),
        migrations.AlterField(
            model_name='qasignalitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
