# Generated by Django 4.2.30 on 2026-09-04 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_qa_signal_model_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusagelog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_logs', to='core.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='tokenusagelog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_logs', to='core.task', verbose_name='任务'),
        ),
    ]
