# Generated by Django 4.2.30 on 2026-09-06 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_qa_tokenusagelog_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAChartSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_method', models.CharField(max_length=20, verbose_name='评价方法')),
                ('study_labels', models.JSONField(default=dict, verbose_name='自定义文献名 {ref_id: label}')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_chart_settings', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '图表设置',
                'verbose_name_plural': '图表设置',
                'db_table': 'plat_qa_chart_settings',
                'unique_together': {('project', 'quality_method')},
            },
        ),
    ]
