# Generated by Django 4.2.30 on 2026-09-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_qa_chart_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='status',
            field=models.CharField(choices=[('pending', '未开始'), ('in_progress', '进行中'), ('stopped', '已停止'), ('completed', '已完成'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='stagestep',
            name='status',
            field=models.CharField(choices=[('pending', '未开始'), ('in_progress', '进行中'), ('stopped', '已停止'), ('completed', '已完成'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('queuing', '排队等待'), ('pending', '等待中'), ('running', '运行中'), ('waiting_user', '等待用户操作'), ('stopping', '正在停止'), ('stopped', '已停止'), ('completed', '已完成'), ('failed', '失败'), ('superseded', '已被续传替代')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
