# Generated by Django 5.2.17 on 2026-09-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_system_operation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='业务幂等键'),
        ),
    ]
