# Generated by Django 4.2.30 on 2026-09-09 17:43

import core.feedback.models
import core.feedback.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0021_system_operation_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(editable=False, max_length=40, unique=True, verbose_name='反馈编号')),
                ('reporter_user_id', models.PositiveBigIntegerField(verbose_name='提交用户ID快照')),
                ('reporter_username', models.CharField(max_length=150, verbose_name='提交用户名快照')),
                ('category', models.CharField(choices=[('problem', '遇到问题'), ('suggestion', '改进建议')], max_length=20, verbose_name='反馈类型')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('status', models.CharField(choices=[('new', '待处理'), ('reviewing', '处理中'), ('resolved', '已解决'), ('rejected', '无效')], default='new', max_length=20, verbose_name='状态')),
                ('page_path', models.CharField(blank=True, max_length=500, verbose_name='页面路径')),
                ('route_name', models.CharField(blank=True, max_length=100, verbose_name='路由名称')),
                ('client_request_id', models.UUIDField(verbose_name='客户端幂等ID')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='技术上下文')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理员备注')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='core.project', verbose_name='关联项目')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_feedback_items', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
                'db_table': 'plat_user_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackDailyQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_date', models.DateField(verbose_name='配额日期')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用次数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_daily_quotas', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '反馈每日配额',
                'verbose_name_plural': '反馈每日配额',
                'db_table': 'plat_feedback_daily_quota',
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=core.feedback.storage.FeedbackStorage(), upload_to=core.feedback.models.feedback_attachment_path, verbose_name='图片')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('mime_type', models.CharField(max_length=50, verbose_name='MIME类型')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='文件大小')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('width', models.PositiveIntegerField(verbose_name='宽度')),
                ('height', models.PositiveIntegerField(verbose_name='高度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.userfeedback', verbose_name='反馈')),
            ],
            options={
                'verbose_name': '反馈图片',
                'verbose_name_plural': '反馈图片',
                'db_table': 'plat_feedback_attachment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['user', 'created_at'], name='feedback_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['status', 'created_at'], name='feedback_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='userfeedback',
            constraint=models.UniqueConstraint(fields=('reporter_user_id', 'client_request_id'), name='feedback_user_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='feedbackdailyquota',
            constraint=models.UniqueConstraint(fields=('user', 'quota_date'), name='feedback_daily_quota_uniq'),
        ),
    ]
