# Generated by Django 5.2.17 on 2026-09-15 09:38

import django.db.models.deletion
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.db import migrations, models


def backfill_unique_account_emails(apps, schema_editor):
    """Backfill only unambiguous valid historical emails; leave conflicts for audit."""
    User = apps.get_model('auth', 'User')
    AccountEmail = apps.get_model('account', 'AccountEmail')

    candidates = {}
    for user_id, raw_email in User.objects.exclude(email='').values_list('id', 'email').iterator():
        normalized = (raw_email or '').strip().lower()
        try:
            validate_email(normalized)
        except ValidationError:
            continue
        candidates.setdefault(normalized, []).append(user_id)

    occupied_emails = set(AccountEmail.objects.values_list('normalized_email', flat=True))
    occupied_users = set(AccountEmail.objects.values_list('user_id', flat=True))
    rows = []
    for normalized, user_ids in candidates.items():
        if len(user_ids) != 1 or normalized in occupied_emails or user_ids[0] in occupied_users:
            continue
        rows.append(AccountEmail(
            user_id=user_ids[0],
            email=normalized,
            normalized_email=normalized,
        ))
    AccountEmail.objects.bulk_create(rows, batch_size=500, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    # Backfilled identities may have become verified or otherwise used after deployment.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('email_activation', '邮箱激活')], default='email_activation', max_length=32, verbose_name='用途')),
                ('token_digest', models.CharField(max_length=64, unique=True, verbose_name='Token 摘要')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='作废时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='最近发送时间')),
                ('send_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='发送尝试次数')),
                ('last_error', models.CharField(blank=True, default='', max_length=255, verbose_name='最近发送错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to='account.accountemail', verbose_name='邮箱身份')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_verification_tokens', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '账户验证 Token',
                'verbose_name_plural': '账户验证 Token',
                'db_table': 'plat_accountverificationtoken',
                'indexes': [models.Index(fields=['user', 'purpose', '-created_at'], name='acct_token_user_idx'), models.Index(fields=['expires_at'], name='acct_token_expiry_idx')],
            },
        ),
        migrations.RunPython(backfill_unique_account_emails, noop_reverse),
    ]
