# Generated by Django 5.2.17 on 2026-09-15 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverificationtoken',
            name='purpose',
            field=models.CharField(
                choices=[
                    ('email_activation', '邮箱激活'),
                    ('password_reset', '密码重置'),
                ],
                default='email_activation',
                max_length=32,
                verbose_name='用途',
            ),
        ),
        migrations.CreateModel(
            name='AccountEmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254, verbose_name='新邮箱')),
                ('normalized_new_email', models.CharField(db_index=True, max_length=254, verbose_name='规范化新邮箱')),
                ('token_digest', models.CharField(max_length=64, unique=True, verbose_name='Token 摘要')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='作废时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='最近发送时间')),
                ('send_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='发送尝试次数')),
                ('last_error', models.CharField(blank=True, default='', max_length=255, verbose_name='最近发送错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='account_email_change_requests',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='用户',
                    ),
                ),
            ],
            options={
                'verbose_name': '邮箱变更请求',
                'verbose_name_plural': '邮箱变更请求',
                'db_table': 'plat_accountemailchangerequest',
                'indexes': [
                    models.Index(fields=['user', '-created_at'], name='acct_emailchg_user_idx'),
                    models.Index(fields=['expires_at'], name='acct_emailchg_expiry_idx'),
                ],
            },
        ),
    ]
