"""
Django settings for platform_backend project.

Generated by 'django-admin startproject'; maintained for Django 4.2 / Python 3.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

def _csv_env(name, default=''):
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


APP_ENV = os.getenv('APP_ENV', 'development').lower()
debug_default = 'False' if APP_ENV == 'production' else 'True'
DEBUG = os.getenv('DJANGO_DEBUG', debug_default).lower() not in ('false', '0', 'no')

# 生产环境必须通过环境变量提供；本地开发使用明确的非生产回退值。
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DEBUG=False')
    SECRET_KEY = 'django-insecure-local-development-only'

ALLOWED_HOSTS = _csv_env('DJANGO_ALLOWED_HOSTS') or (['*'] if DEBUG else [])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_celery_results',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise：生产环境(DEBUG=False)下托管前端静态资源，紧跟 SecurityMiddleware 之后
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'platform_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'web', 'dist'),   # Vite 构建产物
            os.path.join(BASE_DIR, 'templates'),      # 自定义 Admin 模板
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'platform_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# MySQL configuration (set these env vars on server)
#   DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'data_extraction'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'CONN_MAX_AGE': 60,  # 60秒后重建连接，避免无限复用失效连接
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Vite 构建产物中的 assets 目录作为额外静态文件来源
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'web', 'dist', 'assets'),
] if os.path.isdir(os.path.join(BASE_DIR, 'web', 'dist', 'assets')) else []

# ---------------------------------------------------------------------------
# WhiteNoise：让 Django 在生产环境(DEBUG=False)下也能直接托管前端静态资源，
# 无需 nginx / Node。前端 index.html 引用的是 /assets/*.js、/favicon.svg 等根路径资源，
# 通过 WHITENOISE_ROOT 把整个 web/dist 挂到根 URL 上即可命中。
# ---------------------------------------------------------------------------
_WHITENOISE_DIST = os.path.join(BASE_DIR, 'web', 'dist')
if os.path.isdir(_WHITENOISE_DIST):
    WHITENOISE_ROOT = _WHITENOISE_DIST
# 用带压缩+缓存清单的存储后端（collectstatic 时生成 .gz/.br 与带哈希文件名）
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
# index.html 不做长缓存，保证前端更新后能及时刷新
WHITENOISE_INDEX_FILE = False
WHITENOISE_MAX_AGE = 3600

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 允许同源 iframe 加载（PDF 在 <iframe> 中预览需要 SAMEORIGIN 而非 DENY）
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# 计费常量（阶段二）
# ============================================================================

# 1 credit = N tokens（可调整，历史数据按写入时的快照结算）
BILLING_CREDIT_TOKEN_RATIO = int(os.getenv('BILLING_CREDIT_TOKEN_RATIO', '1000'))

# 注册时自动赠送的初始免费额度（credits）
BILLING_FREE_CREDITS_ON_REGISTER = int(os.getenv('BILLING_FREE_CREDITS_ON_REGISTER', '200'))

# 余额不足时的预估每篇 credits（阶段三接入计费后用于预扣估算）
BILLING_ESTIMATE_CREDITS_PER_REF = int(os.getenv('BILLING_ESTIMATE_CREDITS_PER_REF', '2'))

# ============================================================================
# 阶段五：注册防刷配置
# ============================================================================

# 同一 IP 在窗口期内最多允许成功注册的账号数（超出返回 429）
REGISTER_IP_LIMIT = int(os.getenv('REGISTER_IP_LIMIT', '3'))

# 限流窗口（小时），默认 24 小时
REGISTER_IP_WINDOW_HOURS = int(os.getenv('REGISTER_IP_WINDOW_HOURS', '24'))

# 邮箱验证开关（True=注册时必须填写并发送验证邮件，False=邮箱选填跳过验证）
# 当前默认关闭，后续接入 SMTP 后再开启
REQUIRE_EMAIL_VERIFICATION = os.getenv('REQUIRE_EMAIL_VERIFICATION', 'false').lower() == 'true'

# ============================================================================
# 阶段四：全局 AI 筛选并发控制
# ============================================================================

# 全局最大线程槽数（所有正在运行的 ai_screen 任务占用线程数之和上限）
AI_SCREEN_MAX_GLOBAL_THREADS = int(os.getenv('AI_SCREEN_MAX_GLOBAL_THREADS', '64'))

# 普通用户默认并发线程数（未设置 concurrency_limit 时的 fallback）
AI_SCREEN_DEFAULT_CONCURRENCY = int(os.getenv('AI_SCREEN_DEFAULT_CONCURRENCY', '2'))

# 管理员/超管并发线程数
AI_SCREEN_ADMIN_CONCURRENCY = int(os.getenv('AI_SCREEN_ADMIN_CONCURRENCY', '16'))

# 排队等待时重试间隔（秒）
AI_SCREEN_QUEUE_RETRY_INTERVAL = int(os.getenv('AI_SCREEN_QUEUE_RETRY_INTERVAL', '30'))

# 排队最大等待次数（超出则任务失败）
AI_SCREEN_QUEUE_MAX_RETRIES = int(os.getenv('AI_SCREEN_QUEUE_MAX_RETRIES', '120'))  # 120×30s = 1 小时

# Django REST Framework 配置
REST_FRAMEWORK = {
    # 认证方式
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # Session 认证
    ],

    # 默认权限：必须登录
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    # 分页配置
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,

    # 异常处理
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

# 登录相关 URL
LOGIN_URL = '/api/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/api/auth/login/'

# Celery Configuration Options
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'django-db')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_BROKER_POOL_LIMIT = 1  # 限制 broker 连接池，避免 prefork 模型下竞争
CELERY_RESULT_DB_SHORT_LIVED_SESSIONS = True  # 每次任务结果写入后关闭会话，避免连接泄漏
CELERY_IMPORTS = ('core.quality.tasks',)

# CORS Settings：开发环境允许跨域，生产环境必须显式配置白名单。
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = _csv_env('CORS_ALLOWED_ORIGINS')

# CSRF 设置（开发环境）
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = _csv_env(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:8000,http://127.0.0.1:8000' if DEBUG else '',
)

# =============================================================================
# 日志配置
# 平台日志同时输出到控制台和文件，便于开发期实时查看
# 日志文件写到项目根目录的 logs/ 下，Celery worker 也复用同一配置
# =============================================================================
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # 保留 Django 内置 logger

    # ── 格式 ──────────────────────────────────────────────────────────────────
    'formatters': {
        # 控制台：简洁带颜色感知（时间 + 级别 + 模块 + 消息）
        'console': {
            'format': '[{asctime}] {levelname:<8} {name} - {message}',
            'datefmt': '%H:%M:%S',
            'style': '{',
        },
        # 文件：完整信息
        'file': {
            'format': '{asctime} [{levelname}] {name} ({process}d/{thread}d) - {message}',
            'datefmt': '%Y-%m-%d %H:%M:%S',
            'style': '{',
        },
    },

    # ── 处理器 ────────────────────────────────────────────────────────────────
    'handlers': {
        # 输出到终端（Django runserver 和 Celery worker 都能看到）
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console',
            'level': 'DEBUG',
        },
        # 平台主日志文件（旋转，单文件最大 20MB，保留 5 个）
        'platform_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'platform.log'),
            'maxBytes': 20 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'file',
            'encoding': 'utf-8',
            'level': 'DEBUG',
        },
        # 单独记录 WARNING 以上的错误，方便排查
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'error.log'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'file',
            'encoding': 'utf-8',
            'level': 'WARNING',
        },
    },

    # ── Logger 树 ─────────────────────────────────────────────────────────────
    'loggers': {
        # Django 自身（HTTP 请求日志、数据库日志等）
        'django': {
            'handlers': ['console', 'platform_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django 数据库查询日志（DEBUG 模式下才打印 SQL）
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',   # 改为 DEBUG 可看每条 SQL，平时太吵关掉
            'propagate': False,
        },
        # 平台核心业务逻辑（executors、scheduler、providers 等）
        'core': {
            'handlers': ['console', 'platform_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Celery 自身
        'celery': {
            'handlers': ['console', 'platform_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Celery 任务（celery.task.*）
        'celery.task': {
            'handlers': ['console', 'platform_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },

    # ── Root logger（兜底，捕获未在上方显式配置的所有模块）──────────────────
    'root': {
        'handlers': ['console', 'platform_file', 'error_file'],
        'level': 'INFO',
    },
}
