"""
Django settings for platform_backend project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_71g+1zhg!ka)5fm(r$54+8q167!!67w%uqc(tg2ut1(gb^9yh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_celery_results',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'platform_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'frontend')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'platform_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# MySQL configuration (set these env vars on server)
#   DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'data_extraction'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'CONN_MAX_AGE': 60,  # 60秒后重建连接，避免无限复用失效连接
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework 配置
REST_FRAMEWORK = {
    # 认证方式
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # Session 认证
    ],
    
    # 默认权限：必须登录
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    # 分页配置
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    
    # 异常处理
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

# 登录相关 URL
LOGIN_URL = '/api/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/api/auth/login/'

# Celery Configuration Options
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_BROKER_POOL_LIMIT = 1  # 限制 broker 连接池，避免 prefork 模型下竞争
CELERY_RESULT_DB_SHORT_LIVED_SESSIONS = True  # 每次任务结果写入后关闭会话，避免连接泄漏

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True # In production, restrict this to specific origins

# CSRF 设置（开发环境）
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']

# =============================================================================
# 日志配置
# 平台日志同时输出到控制台和文件，便于开发期实时查看
# 日志文件写到项目根目录的 logs/ 下，Celery worker 也复用同一配置
# =============================================================================
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # 保留 Django 内置 logger

    # ── 格式 ──────────────────────────────────────────────────────────────────
    'formatters': {
        # 控制台：简洁带颜色感知（时间 + 级别 + 模块 + 消息）
        'console': {
            'format': '[{asctime}] {levelname:<8} {name} - {message}',
            'datefmt': '%H:%M:%S',
            'style': '{',
        },
        # 文件：完整信息
        'file': {
            'format': '{asctime} [{levelname}] {name} ({process}d/{thread}d) - {message}',
            'datefmt': '%Y-%m-%d %H:%M:%S',
            'style': '{',
        },
    },

    # ── 处理器 ────────────────────────────────────────────────────────────────
    'handlers': {
        # 输出到终端（Django runserver 和 Celery worker 都能看到）
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console',
            'level': 'DEBUG',
        },
        # 平台主日志文件（旋转，单文件最大 20MB，保留 5 个）
        'platform_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'platform.log'),
            'maxBytes': 20 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'file',
            'encoding': 'utf-8',
            'level': 'DEBUG',
        },
        # 单独记录 WARNING 以上的错误，方便排查
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'error.log'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'file',
            'encoding': 'utf-8',
            'level': 'WARNING',
        },
    },

    # ── Logger 树 ─────────────────────────────────────────────────────────────
    'loggers': {
        # Django 自身（HTTP 请求日志、数据库日志等）
        'django': {
            'handlers': ['console', 'platform_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django 数据库查询日志（DEBUG 模式下才打印 SQL）
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',   # 改为 DEBUG 可看每条 SQL，平时太吵关掉
            'propagate': False,
        },
        # 平台核心业务逻辑（executors、scheduler、providers 等）
        'core': {
            'handlers': ['console', 'platform_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Celery 自身
        'celery': {
            'handlers': ['console', 'platform_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Celery 任务（celery.task.*）
        'celery.task': {
            'handlers': ['console', 'platform_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },

    # ── Root logger（兜底，捕获未在上方显式配置的所有模块）──────────────────
    'root': {
        'handlers': ['console', 'platform_file', 'error_file'],
        'level': 'INFO',
    },
}
