# Generated by Django 5.2.17 on 2026-10-10 05:55

import core.external_images.models
import core.external_images.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_request_id', models.UUIDField(unique=True, verbose_name='客户端幂等ID')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='来源标识')),
                ('file', models.FileField(blank=True, max_length=500, storage=core.external_images.storage.ExternalImageStorage(), upload_to=core.external_images.models.external_image_upload_path, verbose_name='私有图片')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('mime_type', models.CharField(max_length=50, verbose_name='MIME类型')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='文件大小')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('width', models.PositiveIntegerField(verbose_name='宽度')),
                ('height', models.PositiveIntegerField(verbose_name='高度')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '外部上传图片',
                'verbose_name_plural': '外部上传图片',
                'db_table': 'plat_external_image_upload',
                'ordering': ['-created_at'],
            },
        ),
    ]
